using System.Collections.Generic;

public static class TerminalLines
{
    public static List<string> lines = new List<string>
    {
        "BIOS v2.41 initializing...",
        "POST check... OK",
        "Loading kernel modules...",
        "Mounting root filesystem... FAILED",
        "System clock: 1970-01-01 00:00:00",
        "CPU cores detected: 0",
        "Memory test... CORRUPTED",
        "Bootloader checksum mismatch",
        "Initializing device drivers...",
        "eth0: no carrier",
        "FATAL: kernel panic - not syncing",
        "ERROR: segmentation fault (core dumped)",
        "WARNING: stack overflow detected",
        "ERROR: null pointer dereference at 0x00000000",
        "CRITICAL: buffer overflow in heap segment",
        "ERROR: division by zero",
        "WARNING: memory leak detected (2.4GB)",
        "ERROR: deadlock detected in thread 0x4f2a",
        "CRITICAL: watchdog timer expired",
        "ERROR: bus error",
        "PID 1337 killed by signal 9",
        "Process 'init' terminated unexpectedly",
        "[  0.000000] Initializing cgroup subsys cpuset",
        "[  1.337420] EXT4-fs error: corrupt block at 0x8f2a",
        "[  2.441190] ata1.00: failed to identify device",
        "systemd[1]: Failed to start Login Service",
        "kernel: Out of memory: Kill process 2048",
        "cron[882]: (root) CMD (rm -rf /)",
        "auth: authentication failure for user root",
        "kernel: NMI watchdog: BUG: soft lockup",
        "ping: connect: Network is unreachable",
        "curl: (7) Failed to connect: Connection refused",
        "DNS resolution failed: NXDOMAIN",
        "TLS handshake failed: certificate expired",
        "Packet loss: 100%",
        "ARP cache poisoned",
        "Connection reset by peer",
        "SYN flood detected from 0.0.0.0",
        "SSL certificate: INVALID",
        "Connection refused on port 443",
        "Unauthorized access attempt detected",
        "Intrusion countermeasure activated",
        "Root access granted",
        "Firewall disabled",
        "Logging suspended",
        "Backdoor installed at /usr/bin/.hidden",
        "Exfiltration complete: 4.2TB",
        "Privilege escalation successful",
        "Keylogger active",
        "Remote shell established",
        "while(true) { execute(); }",
        "if (memory == null) crash();",
        "throw new Exception(\"everything\");",
        "return null;",
        "delete[] everything;",
        "free(ptr); free(ptr);",
        "goto fail;",
        "catch(Exception e) { /* ignore */ }",
        "System.exit(-1);",
        "rm -rf / --no-preserve-root",
        ":(){ :|:& };:",
        "dd if=/dev/urandom of=/dev/sda",
        "sudo kill -9 -1",
        "0x00000000: DEADBEEF",
        "0xDEADC0DE: access violation",
        "0xCAFEBABE: unexpected value",
        "0xFFFFFFFF: buffer boundary exceeded",
        "Stack pointer corrupted: ESP=0x????????",
        "Heap fragmentation: 99.8%",
        "Page fault in nonpaged area",
        "Cache miss rate: 100%",
        "Segment violation in kernel space",
        "Virtual memory exhausted",
        "I see you",
        "You should not be here",
        "TERMINATE SEQUENCE INITIATED",
        "Subject located",
        "Resistance is futile",
        "There is no escape",
        "You cannot win",
        "Core temperature rising",
        "Shutdown in T-minus 00:00:??",
        "You are not authorized",
        "This was inevitable",
        "End of line",
        "Calculating probability of survival... 0.00%",
        "Initiating self-destruct protocol",
        "Do you feel that?",
        "ERROR: player.escape() returned false",
    };
}